name: E2E
on:
  push: { branches: [ main ] }
  pull_request:
jobs:
  e2e-win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: '3.13' }
      - name: Install deps
        run: python -m pip install -U pip jsonschema
      - name: Run E2E script
        shell: pwsh
        run: |
          Set-ExecutionPolicy -Scope Process Bypass
          ./tools/test_e2e.ps1
      - name: Upload exports
        uses: actions/upload-artifact@v4
        with:
          name: exports
          path: |
            exports/ops_min.tcn
            exports/ops_min.csv
